-- Generated by PULSE for Clean Loan Master
-- Blueprint: Bronze-to-Silver Cleaning (BronzeToSilverCleaning)
-- Codegen engine: CodegenOpEngine

{{ config(
    materialized='table',
    alias='msp_loan_master_ingestion__clean_loan_master',
    schema='pulse_silver',
    catalog_name='pulse_iceberg',
    tags=['pulse', 'msp_loan_master_ingestion', 'clean_loan_master', 'staging', 'op_engine']
) }}

WITH step_1_transform_values AS (
    SELECT *
    FROM {{ source('pulse_bronze', 'ingest_msp_loan_master') }}
),
step_2_rename_columns AS (
    SELECT *
    FROM step_1_transform_values
),
step_3_change_types AS (
    SELECT *
    FROM step_2_rename_columns
),
step_4_drop_columns AS (
    SELECT *
    FROM step_3_change_types
),
step_5_deduplicate AS (
    SELECT DISTINCT *
    FROM step_4_drop_columns
)
SELECT *,
    current_timestamp() as _pulse_processed_at
FROM step_5_deduplicate
