-- Generated by PULSE for CleanLoanMaster
-- Blueprint: Bronze-to-Silver Cleaning (BronzeToSilverCleaning)
-- Codegen engine: CodegenOpEngine

{{ config(
    materialized='table',
    alias='msp_loan_master_ingestion__cleanloanmaster',
    schema='pulse_silver',
    catalog_name='pulse_iceberg',
    tags=['pulse', 'msp_loan_master_ingestion', 'cleanloanmaster', 'staging', 'op_engine']
) }}

WITH step_1_transform_values AS (
    SELECT *
    FROM {{ source('pulse_bronze', 'ingestloanmaster') }}
),
step_2_rename_columns AS (
    SELECT *
    FROM step_1_transform_values
),
step_3_change_types AS (
    SELECT *
    FROM step_2_rename_columns
),
step_4_drop_columns AS (
    SELECT *
    FROM step_3_change_types
),
step_5_deduplicate AS (
    SELECT *
    FROM step_4_drop_columns
    QUALIFY row_number() OVER (PARTITION BY loan_id ORDER BY loan_id) = 1
)
SELECT *,
    current_timestamp() as _pulse_processed_at
FROM step_5_deduplicate
