# Generated by PULSE for IngestLoanMaster
# Blueprint: File Ingestion (FileIngestion)
# Codegen engine: CodegenOpEngine

from pyspark.sql import SparkSession
from pyspark.sql.functions import *
import os

PULSE_BUSINESS_DATE = os.environ.get('PULSE_BUSINESS_DATE', '{{ ds }}')
PULSE_PROCESSING_TS = os.environ.get('PULSE_PROCESSING_TS', '{{ ts }}')

spark = SparkSession.builder \
    .appName('msp_loan_master_ingestion_ingestloanmaster') \
    .config('spark.sql.adaptive.enabled', 'true') \
    .getOrCreate()

# read-source: PySpark read into 'df' (Mode=GCP_PULSE).
import os
# PULSE CSV inference reads as strings first, infers a guarded schema,
# then rereads with explicit types. This preserves identifier-like
# values such as ZIP/postal codes that Spark's CSV inferSchema would
# otherwise coerce from "06101" to 6101.
from pyspark.sql import functions as F
from pyspark.sql.types import StructType, StructField, StringType, LongType, DoubleType, BooleanType, DateType

def _pulse_quote_column(column_name):
    return "`" + column_name.replace("`", "``") + "`"

def _pulse_infer_csv_schema(spark, source_path, has_header, sep=','):
    raw_df = spark.read \
        .format('csv') \
        .option('header', has_header) \
        .option('inferSchema', 'false') \
        .option('sep', sep) \
        .load(source_path)
    aggregations = []
    aliases_by_column = []
    for idx, column_name in enumerate(raw_df.columns):
        value = F.trim(F.col(_pulse_quote_column(column_name)))
        present = value.isNotNull() & (value != '')
        aliases = {
            'present': f'c{idx}_present',
            'leading_zero_integer': f'c{idx}_leading_zero_integer',
            'boolean': f'c{idx}_boolean',
            'integer': f'c{idx}_integer',
            'decimal': f'c{idx}_decimal',
            'date': f'c{idx}_date',
        }
        aggregations.extend([
            F.sum(F.when(present, 1).otherwise(0)).alias(aliases['present']),
            F.sum(F.when(present & value.rlike(r'^0[0-9]+$'), 1).otherwise(0)).alias(aliases['leading_zero_integer']),
            F.sum(F.when(present & F.lower(value).isin('true', 'false'), 1).otherwise(0)).alias(aliases['boolean']),
            F.sum(F.when(present & value.rlike(r'^-?[0-9]+$'), 1).otherwise(0)).alias(aliases['integer']),
            F.sum(F.when(present & value.rlike(r'^-?([0-9]+\.[0-9]+|[0-9]+)$'), 1).otherwise(0)).alias(aliases['decimal']),
            F.sum(F.when(present & value.rlike(r'^[0-9]{4}-[0-9]{2}-[0-9]{2}$'), 1).otherwise(0)).alias(aliases['date']),
        ])
        aliases_by_column.append((column_name, aliases))

    metrics = raw_df.agg(*aggregations).collect()[0].asDict() if aggregations else {}
    fields = []
    for column_name, aliases in aliases_by_column:
        present_count = int(metrics.get(aliases['present']) or 0)
        leading_zero_integer_count = int(metrics.get(aliases['leading_zero_integer']) or 0)
        boolean_count = int(metrics.get(aliases['boolean']) or 0)
        integer_count = int(metrics.get(aliases['integer']) or 0)
        decimal_count = int(metrics.get(aliases['decimal']) or 0)
        date_count = int(metrics.get(aliases['date']) or 0)

        if present_count == 0 or leading_zero_integer_count > 0:
            data_type = StringType()
        elif boolean_count == present_count:
            data_type = BooleanType()
        elif integer_count == present_count:
            data_type = LongType()
        elif decimal_count == present_count:
            data_type = DoubleType()
        elif date_count == present_count:
            data_type = DateType()
        else:
            data_type = StringType()
        fields.append(StructField(column_name, data_type, True))
    return StructType(fields)

_pulse_source_path = os.environ.get('PULSE_SOURCE_URI', 'gs://pulse-home-lending-dev-files/servicing/msp/msp-loan-master-ingestion/SRC/')
_pulse_has_header = 'true'
_pulse_csv_sep = ','
_pulse_csv_schema = _pulse_infer_csv_schema(spark, _pulse_source_path, _pulse_has_header, _pulse_csv_sep)
df = (spark.read.format('csv')
    .option('header', _pulse_has_header)
    .option('sep', _pulse_csv_sep)
    .schema(_pulse_csv_schema)
    .load(_pulse_source_path))
from pyspark.sql import types as _pulse_T, functions as _pulse_F
for _pulse_f in df.schema.fields:
    if isinstance(_pulse_f.dataType, _pulse_T.BooleanType):
        df = df.withColumn(_pulse_f.name, _pulse_F.col(_pulse_f.name).cast('string'))
# PULSE audit columns (single source of truth: IngestionAuditColumns.java).
from pyspark.sql.functions import current_timestamp, lit, to_date, input_file_name, col
df = (df
    .withColumn('_pulse_ingested_at', current_timestamp())
    .withColumn('_pulse_pipeline', lit('msp_loan_master_ingestion'))
    .withColumn('_pulse_task', lit(os.environ.get('PULSE_TASK_ID', '{{ task.task_id }}')))
    .withColumn('_pulse_run_id', lit(os.environ.get('PULSE_RUN_ID', '{{ run_id }}')))
    .withColumn('_pulse_dag_id', lit(os.environ.get('PULSE_DAG_ID', '{{ dag.dag_id }}')))
    .withColumn('_pulse_business_date', to_date(lit(PULSE_BUSINESS_DATE), 'yyyy-MM-dd'))
    .withColumn('_pulse_source_uri', input_file_name())
    .withColumn('_pulse_processing_ts', col('_metadata.file_modification_time'))
)

# write-sink: PySpark write of 'df' (Mode=GCP_PULSE, layer=bronze, format=iceberg).
import os
PULSE_TARGET_URI = os.environ.get('PULSE_TARGET_URI', 'gs://pulse-home-lending-dev-lake/servicing/msp/msp-loan-master-ingestion/bronze/ingestloanmaster/')
import re as _pulse_re
_pulse_table = 'pulse.pulse_bronze.' + _pulse_re.sub(r'[^A-Za-z0-9_]', '_', PULSE_TARGET_URI.rstrip('/').split('/')[-1])
df.writeTo(_pulse_table).using('iceberg').createOrReplace()

spark.stop()
