-- Generated by PULSE as a tenant-scoped data-plane date dimension.
-- Runtime business-day mutation uses the packaged calendar bundle; this
-- relation exists for downstream dbt/Spark SQL joins and reporting.

{{ config(
    materialized='table',
    alias='date_dim',
    tags=['pulse', 'calendar', 'date_dim', 'tenant_tenant_home_lending', 'domain_servicing']
) }}

WITH date_spine AS (
    SELECT calendar_date
    FROM UNNEST(GENERATE_DATE_ARRAY(DATE '1900-01-01', DATE '2100-12-31', INTERVAL 1 DAY)) AS calendar_date
)
SELECT
    CAST(FORMAT_DATE('%Y%m%d', calendar_date) AS INT64) AS date_key,
    calendar_date,
    FORMAT_DATE('%Y-%m-%d', calendar_date) AS iso_date,
    EXTRACT(YEAR FROM calendar_date) AS year,
    EXTRACT(QUARTER FROM calendar_date) AS quarter,
    EXTRACT(MONTH FROM calendar_date) AS month,
    EXTRACT(DAY FROM calendar_date) AS day_of_month,
    EXTRACT(DAYOFWEEK FROM calendar_date) AS day_of_week,
    FORMAT_DATE('%a', calendar_date) AS day_name_short,
    FORMAT_DATE('%A', calendar_date) AS day_name,
    EXTRACT(ISOWEEK FROM calendar_date) AS iso_week,
    DATE_TRUNC(calendar_date, MONTH) AS month_start_date,
    LAST_DAY(calendar_date) AS month_end_date,
    DATE_TRUNC(calendar_date, QUARTER) AS quarter_start_date,
    DATE_SUB(DATE_ADD(DATE_TRUNC(calendar_date, QUARTER), INTERVAL 3 MONTH), INTERVAL 1 DAY) AS quarter_end_date,
    DATE_TRUNC(calendar_date, YEAR) AS year_start_date,
    DATE_SUB(DATE_ADD(DATE_TRUNC(calendar_date, YEAR), INTERVAL 12 MONTH), INTERVAL 1 DAY) AS year_end_date,
    CASE WHEN EXTRACT(DAYOFWEEK FROM calendar_date) IN (1, 7) THEN true ELSE false END AS is_weekend,
    'tenant-home-lending' AS tenant_id,
    'servicing' AS pulse_domain_slug
FROM date_spine
